version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: solana_index
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  indexer:
    build: .
    depends_on:
      - db
    environment:
      - RPC_URL=http://host.docker.internal:8899
      - DATABASE_URL=postgresql://user:pass@db:5432/solana_index
    command: ["python", "indexer/main.py"]

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - RPC_URL=http://host.docker.internal:8899
      - DATABASE_URL=postgresql://user:pass@db:5432/solana_index

volumes:
  pgdata:
